name: FlaskApp
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Get the repository
      uses: actions/checkout@v4

    - name: Python installation
      uses: actions/setup-python@v5
    - name: Installting the application dependencies
      run: "pip install --quiet --upgrade --requirement requirements.txt"

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Linting the code
      run: |
        flake8 --ignore=E501,E231 *.py
        pylint --errors-only --disable=C0301 --disable=C0326 *.py
