name: FlaskApp
on: [push]

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
    - name: Get the repository
      uses: actions/checkout@v4

    - name: Install Python v3.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        
    - name: Install the dependencies
      run: "pip install --quiet --upgrade --requirement requirements.txt"

    - name: Lint the code
      run: |
        flake8 --ignore=E501,E231 *.py
        pylint --errors-only --disable=C0301 --disable=C0326 *.py

    - name: Unit tests
      run: |
        python -m unittest --verbose --failfast
        
  build:
    needs: lint-test
    runs-on: ubuntu-latest

    steps:
    - name: Get the repository
      uses: actions/checkout@v4
